### ISSUE TITLE
Test::PostgreSQL is racy when choosing port numbers

### ISSUE THREAD

**Issue by cole-h** [TJC/Test-postgresql#40] opened 2021-03-04 21:32 UTC
When running tests that use Test::PostgreSQL with yath and a high amount
of jobs (reproduced with 16), sometimes tests can fail with colliding
port numbers:

    ( STDERR )  job 11    Failed to start postgres on port 15442: Failed to open /tmp/nix-shell.1ytszg/yath-14161-MqDHWh/tmp/NclbJE/pgtest.prkeW/data/postmaster.pid: No such file or directory at /nix/store/ka5mvpfzgc9z709sx9bljlm7691n2hgm-hydra-perl-deps/lib/perl5/site_perl/5.32.0/Test/PostgreSQL.pm line 429.
    ( STDERR )  job 12    Failed to start postgres on port 15442: Failed to open /tmp/nix-shell.1ytszg/yath-14161-MqDHWh/tmp/xv6Jwh/pgtest.prkeW/data/postmaster.pid: No such file or directory at /nix/store/ka5mvpfzgc9z709sx9bljlm7691n2hgm-hydra-perl-deps/lib/perl5/site_perl/5.32.0/Test/PostgreSQL.pm line 429.

This can be somewhat worked around by setting the base_port with
a random number, but this only decreases the likelihood and doesn't
totally protect against this.

**Comment by TJC** [comment] 2021-03-05 00:14
Hmm, this is probably due to https://github.com/TJC/Test-postgresql/blob/master/lib/Test/PostgreSQL.pm#L391

ie. it only makes `10` attempts to find a good port and then gives up.

For making a fix, I'd suggest:
- try random ports instead of next-increment
- or at least try random increments (say 1-99), rather than a fixed +1

**Comment by TJC** [comment] 2021-03-05 00:30
Can you try the branch from #41 and let me know if that solves the issue?

**Comment by grahamc** [comment] 2021-08-12 14:06
This seemed to solve it for a bit, but I'm continuing to see this issue when running my test suite with -j32. This is the log output from my test suite:

```
( STDERR )  job 15    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/2kvLfb/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 10    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/jh9cXh/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 23    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/e8ZltE/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 31    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/KVqXat/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 19    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/497nke/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 20    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/gOHnOC/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 26    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/zpJaZX/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 27    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/bRKKDV/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 21    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/NNCBFi/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 24    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/aR6ohf/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 16    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/y1UoEX/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 33    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/Vmr6QL/pgtest.E_1rT/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 22    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/AlSqRi/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 34    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/s37wtC/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 32    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/hjsZHA/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 30    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/iLFUvv/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 35    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/NMGgUD/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
( STDERR )  job 18    Failed to start postgres on port 15442: Failed to open /tmp/yath-682680-zX1UoJ/tmp/lCpvqh/pgtest.eQx4F/data/postmaster.pid: No such file or directory at /nix/store/aaxv5p916sncvcaqlc59xclcbzzqlrkq-hydra-perl-deps/lib/perl5/site_perl/5.32.1/Test/PostgreSQL.pm line 429.
```

**Comment by TJC** [comment] 2021-08-13 02:03
Thanks for the report. I hope one of the other maintainers of this library can jump in to help.

**Comment by TJC** [comment] 2021-08-13 02:05
cc @nohuhu @SysPete

**Comment by grahamc** [comment] 2021-08-13 02:14
I wonder if it would be sufficient to only listen on a unix domain socket, and if users of the library could consume that easily enough.

**Comment by nohuhu** [comment] 2021-08-13 18:10
@TJC I hear ye, will try to circle back at this next week. Crunch mode at $work now...

**Comment by nohuhu** [comment] 2021-08-20 01:00
I spent some time playing with this issue, and here's what I found:

* It is reproducible with no special setup on MacOS, merely by running our test suite with `yath`. Fails reliably every time for me.
* The error we are printing is misleading; the issue is not with the port collisions but rather with Postgres trying to open its IPC socket and failing because the path is too long. I found the real culprit by capturing and printing Postgres server log before it got cleaned up, it was not apparent otherwise.
* The Unix socket path length is limited to a value hardcoded in the system; for Linux it's 108 characters, for MacOS it's 103 chars.
* The issue itself seems to be caused by `yath` running every test script in isolation and overriding '$TMPDIR` with a localized value that is scoped to that particular test script; this works fine for regular files but fails for Unix sockets.

The fix itself is rather simple: check if `base_dir` path is longer than certain value, and if it is, generate a shorter path in a separate temporary directory. See https://github.com/TJC/Test-postgresql/pull/42

@grahamc @cole-h Could you please check out the code from https://github.com/nohuhu/Test-postgresql/tree/fix-yath and see if it works with your test suite at the concurrency levels you are using? That'd be helpful to confirm that I root caused the issue correctly.

**Comment by nohuhu** [comment] 2021-08-20 01:13
Also as a heads-up, I won't be responding to this thread until next week. I'll check back when I have a chance.

**Comment by grahamc** [comment] 2021-08-21 01:17
:+1: That does it!

-j32:

```
                                  Yath Result Summary
----------------------------------------------------------------------------------------
     File Count: 38
Assertion Count: 535
      Wall Time: 10.67 seconds
       CPU Time: 192.33 seconds (usr: 0.35s | sys: 0.03s | cusr: 160.56s | csys: 31.39s)
      CPU Usage: 1802%
    -->  Result: PASSED  <--
```

-j4:

```
                                  Yath Result Summary
---------------------------------------------------------------------------------------
     File Count: 38
Assertion Count: 535
      Wall Time: 33.75 seconds
       CPU Time: 107.52 seconds (usr: 0.29s | sys: 0.03s | cusr: 92.70s | csys: 14.50s)
      CPU Usage: 318%
    -->  Result: PASSED  <--
```

thank you very much!

**Comment by SysPete** [comment] 2022-02-17 09:18
closed by merge of #42

**Closed by SysPete** 2022-02-17 09:18 UTC

**Comment by cole-h** [comment] 2022-02-17 21:22
Thanks a lot all involved! Would it be possible to cut a new release with this? 🙏

**Comment by nohuhu** [comment] 2022-02-18 00:57
@cole-h Tried to do just that and realized my Perl-fu is not as it used to be... See https://github.com/TJC/Test-postgresql/issues/43.

**Comment by TJC** [comment] 2022-02-18 01:03
👀
